version: '3'

tasks:
  default:
    desc: "Default task to list all available tasks"
    cmds:
      - go-task --list

  create:
    desc: "Install dependencies for k3s on LXC with LXD and configure local machine"
    cmds:
      - task: create_cluster
      - task: local_configure
    interactive: true

  create_cluster:
    desc: "Install dependencies for k3s on LXC with LXD"
    cmds:
      - ANSIBLE_CONFIG=./ansible/ansible.cfg ansible-playbook -i ./ansible/inventories/inventory.yml ./ansible/playbooks/lxd_cluster_setup.yml
    interactive: true

  local_configure:
    desc: "Configure local machine to interact with LXD cluster"
    cmds:
      - ANSIBLE_CONFIG=./ansible/ansible.cfg ansible-playbook -i ./ansible/inventories/inventory.yml --limit localhost --connection=local --extra-vars "ansible_user=admin lxd_cluster_password=password bootstrap_address=10.10.10.2" --ask-become-pass ./ansible/playbooks/configure_local_lxd.yml
    interactive: true

  destroy:
    desc: "Uninstall dependencies for k3s on LXC with LXD"
    cmds:
      - ANSIBLE_CONFIG=./ansible/ansible.cfg ansible-playbook -i ./ansible/inventories/inventory.yml ./ansible/playbooks/lxd_cluster_teardown.yml
    interactive: true







